// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW2N4IkizMuMs7-ZLe_Wp8BTNAyrrqdWc',
    appId: '1:541468709781:web:35638a6272166a9c8fdc9c',
    messagingSenderId: '541468709781',
    projectId: 'health-56f14',
    authDomain: 'health-56f14.firebaseapp.com',
    storageBucket: 'health-56f14.firebasestorage.app',
    measurementId: 'G-7GW8TP59GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWT6dzWQabMrGd7DjjkJKPiKpIU1bUsy4',
    appId: '1:541468709781:android:7d768c3b07ca0ba78fdc9c',
    messagingSenderId: '541468709781',
    projectId: 'health-56f14',
    storageBucket: 'health-56f14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnykU_ci5SW5Bg9SUnj0rDb5U07JiD80',
    appId: '1:541468709781:ios:7459ccb6601384448fdc9c',
    messagingSenderId: '541468709781',
    projectId: 'health-56f14',
    storageBucket: 'health-56f14.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnykU_ci5SW5Bg9SUnj0rDb5U07JiD80',
    appId: '1:541468709781:ios:7459ccb6601384448fdc9c',
    messagingSenderId: '541468709781',
    projectId: 'health-56f14',
    storageBucket: 'health-56f14.firebasestorage.app',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW2N4IkizMuMs7-ZLe_Wp8BTNAyrrqdWc',
    appId: '1:541468709781:web:5132bf373451d7b48fdc9c',
    messagingSenderId: '541468709781',
    projectId: 'health-56f14',
    authDomain: 'health-56f14.firebaseapp.com',
    storageBucket: 'health-56f14.firebasestorage.app',
    measurementId: 'G-SYSQXSDCDB',
  );

}